### ISSUE TITLE
Unable to run main.py(D-PEDRA) 

### ISSUE THREAD

**Issue by JaysonZhang1997** [aqeelanwar/PEDRA#70]
Hi sir, i'm getting this error when attempting to run the main.py file. It stopped and couldn't open UE file. Hoping u can help me out with this.
![image](https://user-images.githubusercontent.com/75314646/101646821-f968a680-3a72-11eb-893b-3e8782727dd7.png)

**Comment by JustinLeFever** [comment]
I have the same exact issue. This happens with other environments as well. I have put the indoor_complex and indoor_pyramid enivronments into the unreal_envs folder and changed the config accordingly, but this exact thing happens. Nothing actually launches, unreal engine doesn't even open. However, the single drone branch works just fine (apart from some package issues in the requirements text files that I had to work around).

Also, trying to run 'pip install requirements_gpu.txt' or 'pip install requirements_cpu.txt' in the multi drone version yields the error: 
ERROR: Could not find a version that satisfies the requirement requirements_gpu.txt
ERROR: No matching distribution found for requirements_gpu.txt

This doesn't happen in the single drone version. Not sure if its a big deal for me anyways though since I already installed the packages from the single drone version, but it might be a noteworthy bug.

**Comment by aqeelanwar** [comment]
@JaysonZhang1997 
The issue has been resolved. The problem was in the start_environment module in the aux_functions.py. 
`# env_process = []
    env_process = subprocess.Popen(path)`
You can either pull from the repo, or fix the issue by changing the lines to the above ones.

Let me know if the issue still persists.

**Comment by aqeelanwar** [comment]
@JustinLeFever 
Regarding the requirements.txt, did you try 
`pip install -r requirements.txt`

**Comment by JustinLeFever** [comment]
@aqeelanwar 
Aha I somehow managed to forget the '-r' lol. Thanks, that worked for me. And thank you for getting back to me, very much appreciated.

**Comment by aqeelanwar** [comment]
@JustinLeFever 
No problem.

@JaysonZhang1997 
Were you able to resolve the issue?

**Comment by JaysonZhang1997** [comment]
> @JustinLeFever
> No problem.
> 
> @JaysonZhang1997
> Were you able to resolve the issue?

![image](https://user-images.githubusercontent.com/75314646/102228085-404c1580-3f25-11eb-86eb-f87cb006d5f5.png)
I was too busy some time ago. I just tried it and it didn't work.I deleted settings.json and tried again, but still failed. Thank you for your patience.

**Comment by JaysonZhang1997** [comment]
Hi sir, it works on train/DeepQLearning mode.

> @JustinLeFever
> No problem.
> 
> @JaysonZhang1997
> Were you able to resolve the issue?

Hi sir, it works on train/DeepQLearning mode.
